src/Web/WebMVC/Controllers/ApplicationEventChannelController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Notifications.Core.Mediator;
using Notifications.Core.Notifications;
using Subscribing.Application.Commands;
using Subscribing.Application.Queries;
using Subscribing.Application.Queries.ViewModels;
using Subscribing.Domain.Interfaces.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMVC.Resources;
using WebMVC.Resources.Extensions;
using WebMVC.ViewModels;

namespace WebMVC.Controllers
{
    [Authorize(AuthenticationSchemes = "OpenIdConnect")]
    public class ApplicationEventChannelController : ControllerBase
    {
        private readonly IApplicationEventQueries _applicationEventQueries;
        private readonly IMediatorHandler _mediatorHandler;
        private readonly IMapper _mapper;
        private readonly IChannelRepository _channelRepository;
        public IApplicationEventChannelRepository _applicationEventChannelRepository;

        public ApplicationEventChannelController(
            INotificationHandler<DomainNotification> notifications,

            IApplicationEventQueries applicationEventQueries,
            IMediatorHandler mediatorHandler,
            IMapper mapper,
            IChannelRepository channelRepository,
            IApplicationEventChannelRepository applicationEventChannelRepository)
            : base(notifications, mediatorHandler)
        {
            _applicationEventQueries = applicationEventQueries ?? throw new ArgumentNullException(nameof(applicationEventQueries));
            _mediatorHandler = mediatorHandler ?? throw new ArgumentNullException(nameof(mediatorHandler));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _channelRepository = channelRepository ?? throw new ArgumentNullException(nameof(channelRepository));
            _applicationEventChannelRepository = applicationEventChannelRepository ?? throw new ArgumentNullException(nameof(applicationEventChannelRepository));
        }

        public async Task<IActionResult> Index(Guid applicationEventId)
        {
            var allChannels = _mapper.Map<IEnumerable<ChannelViewModel>>(
                await _channelRepository.GetAllAsync()).Where(x => x.ChannelName != "NotificationsApp");

            var applicationEvent = await _applicationEventQueries.GetApplicationEventByIdAsync(applicationEventId);

            var applicationEventChannelCreateViewModel = new ApplicationEventChannelCreateViewModel();
            applicationEventChannelCreateViewModel.ApplicationEvent = applicationEvent;

            foreach (var channel in allChannels)
            {
                var applicationEventChannel = _mapper.Map<ApplicationEventChannelViewModel>(await _applicationEventChannelRepository.GetByApplicationEventIdAndChannelAsync(applicationEventId, channel.Id));

                if (applicationEventChannel == null)
                    applicationEventChannel = new ApplicationEventChannelViewModel()
                    { ApplicationEventId = applicationEvent.Id, Channel = channel, ChannelId = channel.Id, DelayedSendMinutes = 0, Enabled = false }; // Create Default

                applicationEventChannelCreateViewModel.ApplicationEventChannelViewModels.Add(applicationEventChannel);
            }

            return View(applicationEventChannelCreateViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Save(ApplicationEventChannelCreateViewModel model)
        {
            foreach (var item in model.ApplicationEventChannelViewModels)
            {
                var applicationEventChannel = _mapper.Map<ApplicationEventChannelViewModel>(await _applicationEventChannelRepository.GetByApplicationEventIdAndChannelAsync(item.ApplicationEventId, item.ChannelId));
                if (applicationEventChannel == null)
                    await _mediatorHandler.Send(new CreateApplicationEventChannelCommand(item.ApplicationEventId, item.ChannelId, item.DelayedSendMinutes, item.Enabled, item.RequireAcknowledgement));
                else
                    await _mediatorHandler.Send(new UpdateApplicationEventChannelCommand(item.ApplicationEventId, item.ChannelId, item.DelayedSendMinutes, item.Enabled, item.RequireAcknowledgement));
            }

            if (IsValidOperation())
            {
                this.AddToastMessage("Success", "Application Event Settings Updated", ToastType.Success);
                return RedirectToAction(nameof(ApplicationEventController.Index), "ApplicationEvent");
            }

            foreach (var error in GetNotifications())
            {
                ModelState.AddModelError("Error", error);
                this.AddToastMessage("Error", error, ToastType.Error);
            }

            return RedirectToAction(nameof(ApplicationEventController.Index), "ApplicationEvent");
        }
    }
}

src/Web/WebMVC/Controllers/ApplicationEventChannelTemplateController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Notifications.Core.Mediator;
using Notifications.Core.Notifications;
using Subscribing.Application.Commands;
using Subscribing.Application.Queries.ViewModels;
using Subscribing.Domain.Interfaces.Repositories;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Controllers
{
    [Authorize(AuthenticationSchemes = "OpenIdConnect")]
    public class ApplicationEventChannelTemplateController : ControllerBase
    {
        private readonly IMediatorHandler _mediatorHandler;

        public readonly IChannelRepository _channelRepository;
        public readonly IMapper _mapper;
        public readonly IConfiguration _configuration;
        public readonly IApplicationEventChannelTemplateRepository _applicationEventChannelTemplateRepository;
        public readonly IApplicationEventRepository _applicationEventRepository;

        public ApplicationEventChannelTemplateController(
            INotificationHandler<DomainNotification> notifications,
            IMapper mapper,
            IConfiguration configuration,
            IApplicationEventChannelTemplateRepository applicationEventChannelTemplateRepository,
            IApplicationEventRepository applicationEventRepository,
            IMediatorHandler mediatorHandler,
            IChannelRepository channelRepository
           )
            : base(notifications, mediatorHandler)
        {
            _mapper = mapper;
            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            _applicationEventChannelTemplateRepository = applicationEventChannelTemplateRepository ?? throw new ArgumentNullException(nameof(applicationEventChannelTemplateRepository));
            _applicationEventRepository = applicationEventRepository ?? throw new ArgumentNullException(nameof(applicationEventRepository));
            _mediatorHandler = mediatorHandler ?? throw new ArgumentNullException(nameof(mediatorHandler));
            _channelRepository = channelRepository ?? throw new ArgumentNullException(nameof(channelRepository));
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid applicationEventId, Guid channelId)
        {
            var channels = await _channelRepository.GetAllAsync();
            var selectedChannel = channels.FirstOrDefault(x => x.Id == channelId) ?? channels.FirstOrDefault();

            var applicationEventChannelTemplate = _mapper.Map<ApplicationEventChannelTemplateViewModel>(await _applicationEventChannelTemplateRepository
                .GetByApplicationEventAndChannel(applicationEventId, selectedChannel.Id)) ?? new ApplicationEventChannelTemplateViewModel();

            //In Case of a new  template get the template parameters
            if (applicationEventChannelTemplate.ApplicationEvent == null)
            {
                var applicationEventWithApplicationEventParameters = await _applicationEventRepository
                    .GetManyAsync(x => x.Id == applicationEventId, includeProperties: "ApplicationEventParameters");

                applicationEventChannelTemplate.ApplicationEvent = _mapper.Map<ApplicationEventViewModel>(applicationEventWithApplicationEventParameters.FirstOrDefault());
                applicationEventChannelTemplate.ApplicationEventId = applicationEventChannelTemplate.ApplicationEvent.Id;
            }

            applicationEventChannelTemplate.ChannelsList = new SelectList(channels, "Id", "ChannelName");

            return View(applicationEventChannelTemplate);
        }

        [HttpPost]
        public async Task<JsonResult> SaveTemplate(Guid applicationEventId, Guid channelId, string subject, string body)
        {
            var applicationEventChannelTemplate = _mapper.Map<ApplicationEventChannelTemplateViewModel>(await _applicationEventChannelTemplateRepository.GetByApplicationEventAndChannel(applicationEventId, channelId));
            if (applicationEventChannelTemplate == null)
                await _mediatorHandler.Send(new CreateApplicationEventChannelTemplateCommand(applicationEventId, channelId, "", "", subject, body));
            else
                await _mediatorHandler.Send(new UpdateApplicationEventChannelTemplateCommand(applicationEventId, channelId, "", "", subject, body));

            return IsValidOperation()
               ? Json(new { result = true, responseText = "Template  Created" })
               : Json(new { result = false, responseText = GetFirstErrorMsg() });
        }
    }
}

src/Web/WebMVC/Controllers/ApplicationEventController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Notifications.Core.Mediator;
using Notifications.Core.Notifications;
using Subscribing.Application.Commands;
using Subscribing.Application.Queries;
using Subscribing.Application.Queries.ViewModels;
using Subscribing.Domain.Interfaces.Repositories;
using System;
using System.Threading.Tasks;
using WebMVC.Resources;
using WebMVC.Resources.Extensions;
using WebMVC.ViewModels;

namespace WebMVC.Controllers
{
    [Authorize(AuthenticationSchemes = "OpenIdConnect")]
    public class ApplicationEventController : ControllerBase
    {
        private readonly IApplicationEventQueries _applicationEventQueries;
        private readonly IMediatorHandler _mediatorHandler;
        public IApplicationEventRepository _applicationEventRepository;

        public ApplicationEventController(
            INotificationHandler<DomainNotification> notifications,

            IApplicationEventQueries applicationEventQueries,
            IMediatorHandler mediatorHandler,
            IApplicationEventRepository applicationEventRepository)
            : base(notifications, mediatorHandler)
        {
            _applicationEventQueries = applicationEventQueries ?? throw new ArgumentNullException(nameof(applicationEventQueries));
            _mediatorHandler = mediatorHandler ?? throw new ArgumentNullException(nameof(mediatorHandler));
            _applicationEventRepository = applicationEventRepository ?? throw new ArgumentNullException(nameof(applicationEventRepository));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _applicationEventQueries.GetAllApplicationEventsWithRelatedAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var applicationEvent = await _applicationEventQueries.GetApplicationEventWithRelatedAsync(id);
            if (applicationEvent == null) return BadRequest();

            applicationEvent.SubscriberFiltersList = new SelectList(
                await _applicationEventRepository.GetAllSubscriberFiltersAsync(), "Id", "FilterType");

            return View(applicationEvent);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationEventViewModel model)
        {
            var command = new UpdateApplicationEventCommand(model.Id, model.ApplicationEventName, model.Description);

            await _mediatorHandler.Send(command);

            if (IsValidOperation())
            {
                this.AddToastMessage("Success", "Application Event Updated", ToastType.Success);
                return RedirectToAction("Index", "ApplicationEvent");
            }

            foreach (var error in GetNotifications())
            {
                ModelState.AddModelError("Error", error);
            }
            this.AddToastMessage("Error", GetFirstErrorMsg(), ToastType.Error);

            return RedirectToAction("Create", "ApplicationEvent");
        }

        public IActionResult Create()
        {
            var applicationEvent = new ApplicationEventCreateViewModel();

            applicationEvent.SubscriberFiltersList = new SelectList(
                 _applicationEventQueries.GetAllSubscriberFilterTypes(), "Id", "FilterType");

            return View(applicationEvent);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ApplicationEventCreateViewModel model)
        {
            var command = new CreateApplicationEventCommand(Guid.NewGuid(), model.ApplicationEventName, model.Description);

            await _mediatorHandler.Send(command);

            //Add SubscriberFilter
            foreach (var subscriberFilter in model.SubscriberFilters)
            {
                var addSubscriberFilterCommand = new AddSubscriberFilterCommand(Guid.NewGuid(), subscriberFilter.ApplicationEventId, subscriberFilter.FilterType, subscriberFilter.FilterValue);
                await _mediatorHandler.Send(addSubscriberFilterCommand);
            }

            if (IsValidOperation())
            {
                this.AddToastMessage("Success", "Application Event Created", ToastType.Success);
                return RedirectToAction("Index", "ApplicationEvent");
            }

            foreach (var error in GetNotifications())
            {
                ModelState.AddModelError("Error", error);
                this.AddToastMessage("Error", error, ToastType.Error);
            }

            return RedirectToAction("Create", "ApplicationEvent");
        }

        public async Task<IActionResult> Details(Guid id)
        {
            return View(await _applicationEventQueries.GetApplicationEventByIdAsync(id));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            return View(await _applicationEventQueries.GetApplicationEventByIdAsync(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var command = new RemoveApplicationEventCommand(id);

            await _mediatorHandler.Send(command);

            if (IsValidOperation())
            {
                this.AddToastMessage("Success", "Application Event Deleted", ToastType.Success);
                return RedirectToAction("Index", "ApplicationEvent");
            }

            foreach (var error in GetNotifications())
            {
                ModelState.AddModelError("Error", error);
                this.AddToastMessage("Error", error, ToastType.Error);
            }

            return RedirectToAction("Delete", "ApplicationEvent");
        }
    }
}

src/Web/WebMVC/Views/ApplicationEvent/Create.cshtml
@model ApplicationEventCreateViewModel

@{
    ViewData["Title"] = "Create Application Event";
    var headerList = new List<Header>() {
        new Header() { Controller = "Home", Text = "Back to Home" },
        new Header() { Text = " / " },
        new Header() { Controller = "ApplicationEvent", Text = "Application Event" } };
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Create Application Event</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a>Settings</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Create Application Event</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
            <a class="btn btn-primary" asp-controller="ApplicationEvent" asp-action="Index">Back To List</a>
        </div>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Create Application Event</h5>
                </div>
                <div class="ibox-content">
                    <form method="post" role="form" asp-controller="ApplicationEvent" asp-action="Create">
                        <div class="row">
                            @foreach (var error in ViewData.ModelState.Values.SelectMany(err => err.Errors))
                            {
                                <div class="alert alert-warning" role="alert">
                                    &nbsp;@error.ErrorMessage
                                </div>
                            }
                        </div>
                        <div class="form-group row">
                            <label asp-for="ApplicationEventName" class="col-lg-2 col-form-label">Application Event Name</label>
                            <div class="col-lg-5">
                                <input asp-for="ApplicationEventName" type="text" placeholder="Application Event Name" class="form-control" />
                                <span asp-validation-for="ApplicationEventName" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label asp-for="Description" class="col-lg-2 col-form-label">Description</label>
                            <div class="col-lg-5">
                                <input asp-for="Description" type="text" placeholder="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger" />
                            </div>
                        </div>
                        @*<div id="subscriberFilters">
                            <div class="form-group row">
                                <label asp-for="SubscriberFilters" class="col-lg-2 col-form-label">Subscriber Filter</label>
                                <div class="col-lg-5">
                                    <select asp-for="@Model.SubscriberFilters[0].Fil terType" asp-items="@Model.SubscriberFiltersList" placeholder="" class="form-control subscriberFilterSelect"></select>
                                </div>
                            </div>
                            <div class="form-group row">
                                    <div class="col-lg-5">
                                        <input asp-for="@Model.SubscriberFilters[0].FilterValue" type="text" placeholder="Value" class="form-control" />
                                        <span asp-validation-for="@Model.SubscriberFilters[0].FilterValue" class="text-danger" />
                                    </div>
                                </div>
                            <button id="btnAddFilter" class="btn btn-info btn-sm" type="submit">Add New Filter</button>
                        </div>*@
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <a class="btn btn-white btn-sm" asp-controller="ApplicationEvent" asp-action="Index">Cancel</a>
                                <button class="btn btn-primary btn-sm" type="submit">Save changes</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" />
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2-bootstrap4.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" />
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2-bootstrap4.min.css" />
    </environment>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <environment names="Development">
        <script src="~/lib/select2/dist/js/select2.full.min.js"></script>
    </environment>

    <environment names="Staging,Production">
        <script src="~/lib/select2/dist/js/select2.full.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            var $fields = $('#subscriberFilters');
            $('#btnAddFilter').click(function (e) {
                e.preventDefault();
                $("#subscriberFilters").outerHTML().appendTo($fields);
            });

            $(".subscriberFilterSelect").select2({
                theme: 'bootstrap4',
                placeholder: {
                    id: '-1', // the value of the option
                    text: 'Select an option'
                },
                allowClear: true
            });
        });

        $('.subscriberFilterSelect').val(null).trigger('change');
    </script>
}

src/Web/WebMVC/Views/ApplicationEvent/Delete.cshtml
@model Subscribing.Application.Queries.ViewModels.ApplicationEventViewModel

@{
    ViewData["Title"] = "Delete Application Event";
    var headerList = new List<Header>() {
        new Header() { Controller = "Home", Text = "Back to Home" },
        new Header() { Text = " / " },
        new Header() { Controller = "ApplicationEvent", Text = "Application Event" } };
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Delete Application Event</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a>Settings</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Delete Application Event</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Application Event Details</h5>
                </div>
                <div class="ibox-content">
                    <form method="post" role="form" asp-controller="ApplicationEvent" asp-action="Delete">
                        <h4 class="text-danger">Are you sure you want to delete this?</h4>
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.ApplicationEventName)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.ApplicationEventName)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Description)
                            </dt>
                        </dl>
                        <button class="btn btn-danger" type="submit" asp-route-id="@Model.Id">Delete</button>
                        <a class="btn btn-white" asp-controller="ApplicationEvent" asp-action="Index">Back To List</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/Web/WebMVC/Views/ApplicationEvent/Details.cshtml
@model Subscribing.Application.Queries.ViewModels.ApplicationEventViewModel

@{
    ViewData["Title"] = "Application Event Details";
    var headerList = new List<Header>() {
        new Header() { Controller = "Home", Text = "Back to Home" },
        new Header() { Text = " / " },
        new Header() { Controller = "ApplicationEvent", Text = "Application Event" } };
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2> Application Event Details</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a>Settings</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Application Event Details</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Application Event Details</h5>
                </div>
                <div class="ibox-content">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.ApplicationEventName)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.ApplicationEventName)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Description)
                        </dd>
                        
                    </dl>
                    <a class="btn btn-primary" asp-controller="ApplicationEvent" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn btn-white" asp-controller="ApplicationEvent" asp-action="Index">Back To List</a>
                </div>
            </div>
        </div>
    </div>
</div>

src/Web/WebMVC/Views/ApplicationEvent/Index.cshtml
@model IEnumerable<Subscribing.Application.Queries.ViewModels.ApplicationEventViewModel>

@{
    ViewData["Title"] = "Application Events";
    var headerList = new List<Header>() {
        new Header() { Controller = "Home", Text = "Back to Home" },
        new Header() { Text = " / " },
        new Header() { Controller = "ApplicationEvent", Text = "Application Event" } };
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Application Events</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a>Settings</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Application Events</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Application Event</h5>
                    <div class="ibox-tools">
                        <a class="btn btn-primary btn-xs" asp-controller="ApplicationEvent" asp-action="Create">Create</a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ApplicationEventName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SubscriberFilters)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApplicationEventName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>

                                <td>
                                    <div class="tooltip-helper">
                                        <a class="btn btn-primary btn-sm" asp-controller="ApplicationEvent" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                        <a class="btn btn-white btn-sm" asp-controller="ApplicationEvent" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                        <a class="btn btn-white btn-sm" asp-controller="ApplicationEvent" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        <a class="btn btn-primary btn-circle float-right" data-toggle="tooltip" data-placement="top" title="Edit Parameters" asp-controller="ApplicationEventParameter" asp-action="Index" asp-route-applicationEventId="@item.Id"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-success btn-circle float-right" data-toggle="tooltip" data-placement="top" title="Edit Templates" asp-controller="ApplicationEventChannelTemplate" asp-action="Index" asp-route-applicationEventId="@item.Id"><i class="fa fa-envelope"></i></a>
                                        <a class="btn btn-info btn-circle float-right" data-toggle="tooltip" data-placement="top" title="Settings" asp-controller="ApplicationEventChannel" asp-action="Index" asp-route-applicationEventId="@item.Id"><i class="fa fa-cogs"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {

}